site_name: Saturn 9944

nav:
  - About the Team: index.md
  - Gallery: gallery.md
  - Sponsors: sponsors.md
  - Sponsor Packages: sponsorpackages.md
  - Contact: contact.md

theme:
  logo: assets/saturn9944/SATURN-Logo-Dark-Transparent.png
  favicon: assets/favicon.ico
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: custom
      accent: custom

  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - meta
